# Generated by Django 6.1 on 2026-09-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shipment_pricing_and_offer_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selfie_with_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='selfie_with_id/'),
        ),
    ]
