# Generated by Django 6.1 on 2026-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_selfie_with_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
