# Generated by Django 6.1 on 2026-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehicle_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportoffer',
            name='requested_by_driver',
            field=models.BooleanField(default=False),
        ),
    ]
